platform :ios, '15.0'

target 'TwoPlayerSnake' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK', '~> 11.0'
  pod 'RevenueCat', '~> 5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
